import { Platform, PlatformSpec } from "@/types/ad"

export const platformSpecs: Record<Platform, PlatformSpec> = {
  "ig-feed-square": {
    name: "Instagram Feed (Square)",
    platform: "instagram",
    format: "feed",
    width: 1080,
    height: 1080,
    aspectRatio: "1:1",
    safeZones: { top: 60, bottom: 60, left: 60, right: 60 },
    notes: "Most versatile format. Works on both IG and FB feed.",
  },
  "ig-feed-portrait": {
    name: "Instagram Feed (Portrait)",
    platform: "instagram",
    format: "feed",
    width: 1080,
    height: 1350,
    aspectRatio: "4:5",
    safeZones: { top: 60, bottom: 60, left: 60, right: 60 },
    notes: "Takes up more screen real estate in feed. Preferred for conversion ads.",
  },
  "ig-stories": {
    name: "Instagram Stories",
    platform: "instagram",
    format: "stories",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    safeZones: { top: 250, bottom: 340, left: 60, right: 60 },
    notes: "Top safe zone: username/timestamp UI. Bottom safe zone: swipe-up/CTA button area + reply bar.",
  },
  "fb-stories": {
    name: "Facebook Stories",
    platform: "facebook",
    format: "stories",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    safeZones: { top: 250, bottom: 340, left: 60, right: 60 },
    notes: "Same dimensions as IG Stories. Safe zones identical.",
  },
  tiktok: {
    name: "TikTok Feed",
    platform: "tiktok",
    format: "feed",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    safeZones: { top: 150, bottom: 440, left: 60, right: 200 },
    notes: "Heavier bottom UI (buttons, description, music ticker). Right side has like/comment/share buttons — keep clear.",
  },
  "fb-feed-square": {
    name: "Facebook Feed (Square)",
    platform: "facebook",
    format: "feed",
    width: 1080,
    height: 1080,
    aspectRatio: "1:1",
    safeZones: { top: 60, bottom: 60, left: 60, right: 60 },
    notes: "Same as IG feed square. Cross-post compatible.",
  },
  "fb-feed-landscape": {
    name: "Facebook Feed (Landscape)",
    platform: "facebook",
    format: "feed",
    width: 1200,
    height: 628,
    aspectRatio: "1.91:1",
    safeZones: { top: 60, bottom: 60, left: 60, right: 60 },
    notes: "Standard link preview format. Good for traffic/click campaigns.",
  },
  "fb-feed-portrait": {
    name: "Facebook Feed (Portrait)",
    platform: "facebook",
    format: "feed",
    width: 1080,
    height: 1350,
    aspectRatio: "4:5",
    safeZones: { top: 60, bottom: 60, left: 60, right: 60 },
    notes: "Same as IG portrait. Max vertical real estate in FB feed.",
  },
  "ig-reels-cover": {
    name: "Instagram Reels Cover",
    platform: "instagram",
    format: "reels",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    safeZones: { top: 200, bottom: 400, left: 60, right: 60 },
    notes: "Cover image for Reels. Key content should be in center 60% vertically.",
  },
}

export const platformOptions = Object.entries(platformSpecs).map(
  ([key, spec]) => ({
    value: key as Platform,
    label: spec.name,
    platform: spec.platform,
    dimensions: `${spec.width}x${spec.height}`,
    aspectRatio: spec.aspectRatio,
  })
)
